// Code generated by go-codegen go_accessor; DO NOT EDIT.

package kabusapi

import (
	http "net/http"
	url "net/url"
)

func (m *Client) OverwriteRestURLBase(s url.URL) {
	m.restBaseURL = s
}

func (m *Client) OverwritePushURLBase(s url.URL) {
	m.pushBaseURL = s
}

func (m *Client) SetUserAgent(s string) {
	m.userAgent = s
}

func (m *Client) SetHTTPClient(s *http.Client) {
	m.httpClient = s
}
